### ISSUE TITLE
Wrong values of the rating not sent back after POST request

### ISSUE THREAD

**Issue by simibac** [PokeMate/backend#26]
The response should return the average of all ratings that this pokemon has received for `name`, `image`, `rating`.

![Screenshot 2020-04-25 at 14 53 11](https://user-images.githubusercontent.com/15369592/80280493-af5dcb00-8704-11ea-9a24-1feda6fdca58.png)

**Comment by simibac** [comment]
same for GET request on `/rating/1`

**Comment by Lochindaal** [comment]
API requires integers (0.x will be rounded down to 0)
